/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CinemaJMK48;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.DayOfWeek;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
/**
 *
 * @author NERO
 */
public class Cinema extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cinema.class.getName());

    /**
     * Creates new form kursibioskop
     */
    public Cinema() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tabel_client.getModel();
        model.setRowCount(0);
                
    }

    int filmDipilih = -1;
    int kursiDipilih;
    boolean[][] kursiTerisi = new boolean[4][24];
    
    public String kursi() {
        if(belumPilihFilm()) {
            JOptionPane.showMessageDialog(
            this,
            "Pilih film terlebih dahulu!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
            
            return null;
        }
        
        char baris = (char) ('A' + (kursiDipilih/6));
        int nomor = (kursiDipilih%6) + 1;
        String nomorKursi = baris + String.valueOf(nomor);
        return nomorKursi;
    }
    
    public boolean belumPilihFilm() {
        return filmDipilih == -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_kursi_A1 = new javax.swing.JButton();
        btn_kursi_A2 = new javax.swing.JButton();
        btn_kursi_A3 = new javax.swing.JButton();
        btn_kursi_A4 = new javax.swing.JButton();
        btn_kursi_A5 = new javax.swing.JButton();
        btn_kursi_A6 = new javax.swing.JButton();
        btn_kursi_B1 = new javax.swing.JButton();
        btn_kursi_B2 = new javax.swing.JButton();
        btn_kursi_B3 = new javax.swing.JButton();
        btn_kursi_B4 = new javax.swing.JButton();
        btn_kursi_B5 = new javax.swing.JButton();
        btn_kursi_B6 = new javax.swing.JButton();
        btn_kursi_C1 = new javax.swing.JButton();
        btn_kursi_C2 = new javax.swing.JButton();
        btn_kursi_C3 = new javax.swing.JButton();
        btn_kursi_C4 = new javax.swing.JButton();
        btn_kursi_C5 = new javax.swing.JButton();
        btn_kursi_C6 = new javax.swing.JButton();
        btn_kursi_D1 = new javax.swing.JButton();
        btn_kursi_D2 = new javax.swing.JButton();
        btn_kursi_D3 = new javax.swing.JButton();
        btn_kursi_D4 = new javax.swing.JButton();
        btn_kursi_D5 = new javax.swing.JButton();
        btn_kursi_D6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDENTITAS = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        input_nama = new javax.swing.JTextField();
        input_nohp = new javax.swing.JTextField();
        btn_pesan = new javax.swing.JButton();
        lbl_kursi = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_film = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        input_tanggal = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        lbl_gif = new javax.swing.JLabel();
        cb_jamTayang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_client = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        btn_film_500daysofsummer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_film_thedarkknight = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_film_interstellar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_film_avengersdoomsday = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_kursi_A1.setText("A1");
        btn_kursi_A1.addActionListener(this::btn_kursi_A1ActionPerformed);

        btn_kursi_A2.setText("A2");
        btn_kursi_A2.addActionListener(this::btn_kursi_A2ActionPerformed);

        btn_kursi_A3.setText("A3");
        btn_kursi_A3.addActionListener(this::btn_kursi_A3ActionPerformed);

        btn_kursi_A4.setText("A4");
        btn_kursi_A4.addActionListener(this::btn_kursi_A4ActionPerformed);

        btn_kursi_A5.setText("A5");
        btn_kursi_A5.addActionListener(this::btn_kursi_A5ActionPerformed);

        btn_kursi_A6.setText("A6");
        btn_kursi_A6.addActionListener(this::btn_kursi_A6ActionPerformed);

        btn_kursi_B1.setText("B1");
        btn_kursi_B1.addActionListener(this::btn_kursi_B1ActionPerformed);

        btn_kursi_B2.setText("B2");
        btn_kursi_B2.addActionListener(this::btn_kursi_B2ActionPerformed);

        btn_kursi_B3.setText("B3");
        btn_kursi_B3.addActionListener(this::btn_kursi_B3ActionPerformed);

        btn_kursi_B4.setText("B4");
        btn_kursi_B4.addActionListener(this::btn_kursi_B4ActionPerformed);

        btn_kursi_B5.setText("B5");
        btn_kursi_B5.addActionListener(this::btn_kursi_B5ActionPerformed);

        btn_kursi_B6.setText("B6");
        btn_kursi_B6.addActionListener(this::btn_kursi_B6ActionPerformed);

        btn_kursi_C1.setText("C1");
        btn_kursi_C1.addActionListener(this::btn_kursi_C1ActionPerformed);

        btn_kursi_C2.setText("C2");
        btn_kursi_C2.addActionListener(this::btn_kursi_C2ActionPerformed);

        btn_kursi_C3.setText("C3");
        btn_kursi_C3.addActionListener(this::btn_kursi_C3ActionPerformed);

        btn_kursi_C4.setText("C4");
        btn_kursi_C4.addActionListener(this::btn_kursi_C4ActionPerformed);

        btn_kursi_C5.setText("C5");
        btn_kursi_C5.addActionListener(this::btn_kursi_C5ActionPerformed);

        btn_kursi_C6.setText("C6");
        btn_kursi_C6.addActionListener(this::btn_kursi_C6ActionPerformed);

        btn_kursi_D1.setText("D1");
        btn_kursi_D1.addActionListener(this::btn_kursi_D1ActionPerformed);

        btn_kursi_D2.setText("D2");
        btn_kursi_D2.addActionListener(this::btn_kursi_D2ActionPerformed);

        btn_kursi_D3.setText("D3");
        btn_kursi_D3.addActionListener(this::btn_kursi_D3ActionPerformed);

        btn_kursi_D4.setText("D4");
        btn_kursi_D4.addActionListener(this::btn_kursi_D4ActionPerformed);

        btn_kursi_D5.setText("D5");
        btn_kursi_D5.addActionListener(this::btn_kursi_D5ActionPerformed);

        btn_kursi_D6.setText("D6");
        btn_kursi_D6.addActionListener(this::btn_kursi_D6ActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("PILIH KURSI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_kursi_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btn_kursi_B1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_kursi_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_kursi_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_kursi_D2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_D3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_D4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_D5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_kursi_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_kursi_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_kursi_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_kursi_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_kursi_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_kursi_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_kursi_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_kursi_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_D6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_kursi_A6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kursi_A5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_kursi_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_kursi_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_kursi_A3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_kursi_A4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_kursi_B6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kursi_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_kursi_D6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_kursi_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_B2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_B3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_B4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_B5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_kursi_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_kursi_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_D2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_D3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_D4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_kursi_D5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CINEMA JMK48");
        jLabel1.setToolTipText("");

        jLabel2.setText("NAMA :");

        jLabel4.setText("NO HP :");

        jLabel5.setText("FILM :");

        IDENTITAS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IDENTITAS.setText("IDENTITAS CLIENT");

        jLabel6.setText("KURSI :");
        jLabel6.setMaximumSize(new java.awt.Dimension(55, 16));
        jLabel6.setMinimumSize(new java.awt.Dimension(55, 16));
        jLabel6.setPreferredSize(new java.awt.Dimension(55, 16));

        btn_pesan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pesan.setText("PESAN");
        btn_pesan.addActionListener(this::btn_pesanActionPerformed);

        lbl_kursi.setText(" ");

        lbl_film.setText(" ");

        jLabel15.setText("TANGGAL:");

        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(this::btn_clearActionPerformed);

        lbl_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/waving.gif"))); // NOI18N
        lbl_gif.setText(" ");

        cb_jamTayang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Jam--" }));

        jLabel3.setText("JAM  :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(6, 197, Short.MAX_VALUE)
                                .addComponent(btn_clear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pesan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(input_nama)
                                    .addComponent(input_nohp)
                                    .addComponent(input_tanggal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(lbl_film, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl_kursi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)
                                        .addComponent(cb_jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_gif, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(IDENTITAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(IDENTITAS, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_film, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_kursi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_jamTayang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_gif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {input_nama, jLabel2});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {input_nohp, jLabel4});

        tabel_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "NO HP", "TANGGAL PEMESANAN", "FILM", "JAM TAYANG", "KURSI", "HARGA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_client.getTableHeader().setReorderingAllowed(false);
        tabel_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_clientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_client);
        if (tabel_client.getColumnModel().getColumnCount() > 0) {
            tabel_client.getColumnModel().getColumn(2).setResizable(false);
            tabel_client.getColumnModel().getColumn(6).setResizable(false);
        }

        btn_film_500daysofsummer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/500days.jpg"))); // NOI18N
        btn_film_500daysofsummer.addActionListener(this::btn_film_500daysofsummerActionPerformed);

        jLabel8.setText("Interstellar");

        jLabel9.setText("(500) Days of Summer");

        btn_film_thedarkknight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/darkknight.jpg"))); // NOI18N
        btn_film_thedarkknight.addActionListener(this::btn_film_thedarkknightActionPerformed);

        jLabel10.setText("The Dark Knight");

        btn_film_interstellar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interstellar.jpg"))); // NOI18N
        btn_film_interstellar.addActionListener(this::btn_film_interstellarActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("DAFTAR FILM");

        btn_film_avengersdoomsday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doomsday.jpg"))); // NOI18N
        btn_film_avengersdoomsday.addActionListener(this::btn_film_avengersdoomsdayActionPerformed);

        jLabel16.setText("Avengers: Doomsday");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_film_500daysofsummer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_film_thedarkknight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_film_interstellar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_film_avengersdoomsday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6))))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_film_500daysofsummer, btn_film_interstellar, btn_film_thedarkknight});

        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_film_thedarkknight)
                    .addComponent(btn_film_500daysofsummer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_film_interstellar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_film_avengersdoomsday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_film_500daysofsummer, btn_film_interstellar, btn_film_thedarkknight});

        jScrollPane2.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kursi_A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A1ActionPerformed
        kursiDipilih = 0;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A1ActionPerformed

    private void btn_kursi_A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A2ActionPerformed
        kursiDipilih = 1;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A2ActionPerformed

    private void btn_kursi_A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A3ActionPerformed
        kursiDipilih = 2;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A3ActionPerformed

    private void btn_kursi_A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A4ActionPerformed
        kursiDipilih = 3;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A4ActionPerformed

    private void btn_kursi_A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A5ActionPerformed
        kursiDipilih = 4;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A5ActionPerformed

    private void btn_kursi_A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_A6ActionPerformed
        kursiDipilih = 5;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_A6ActionPerformed

    private void btn_kursi_B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B1ActionPerformed
        kursiDipilih = 6;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B1ActionPerformed

    private void btn_kursi_B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B2ActionPerformed
        kursiDipilih = 7;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B2ActionPerformed

    private void btn_kursi_B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B3ActionPerformed
        kursiDipilih = 8;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B3ActionPerformed

    private void btn_kursi_B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B4ActionPerformed
        kursiDipilih = 9;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B4ActionPerformed

    private void btn_kursi_B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B5ActionPerformed
        kursiDipilih = 10;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B5ActionPerformed

    private void btn_kursi_B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_B6ActionPerformed
        kursiDipilih = 11;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_B6ActionPerformed

    private void btn_kursi_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C1ActionPerformed
        kursiDipilih = 12;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C1ActionPerformed

    private void btn_kursi_C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C5ActionPerformed
        kursiDipilih = 16;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C5ActionPerformed

    private void btn_kursi_C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C4ActionPerformed
        kursiDipilih = 15;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C4ActionPerformed

    private void btn_kursi_C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C3ActionPerformed
        kursiDipilih = 14;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C3ActionPerformed

    private void btn_kursi_C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C2ActionPerformed
        kursiDipilih = 13;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C2ActionPerformed

    private void btn_kursi_C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_C6ActionPerformed
        kursiDipilih = 17;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_C6ActionPerformed

    private void btn_kursi_D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D1ActionPerformed
        kursiDipilih = 18;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D1ActionPerformed

    private void btn_kursi_D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D3ActionPerformed
        kursiDipilih = 20;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D3ActionPerformed

    private void btn_kursi_D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D6ActionPerformed
        kursiDipilih = 23;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D6ActionPerformed

    private void btn_kursi_D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D5ActionPerformed
        kursiDipilih = 22;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D5ActionPerformed

    private void btn_kursi_D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D4ActionPerformed
        kursiDipilih = 21;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D4ActionPerformed

    private void btn_kursi_D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kursi_D2ActionPerformed
        kursiDipilih = 19;
        lbl_kursi.setText(kursi());
    }//GEN-LAST:event_btn_kursi_D2ActionPerformed

    private void btn_film_thedarkknightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_thedarkknightActionPerformed
        lbl_film.setText("The Dark Knight");
        filmDipilih = 1;
        
        cb_jamTayang.removeAllItems();
    cb_jamTayang.addItem("--Pilih Jam--");
    cb_jamTayang.addItem("14:00");
    cb_jamTayang.addItem("17:30");
    cb_jamTayang.addItem("20:45");
    }//GEN-LAST:event_btn_film_thedarkknightActionPerformed

    private void btn_film_500daysofsummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_500daysofsummerActionPerformed
        lbl_film.setText("(500) Days of Summer");
        filmDipilih = 0;
        
        cb_jamTayang.removeAllItems();
    cb_jamTayang.addItem("--Pilih Jam--");
    cb_jamTayang.addItem("13:00");
    cb_jamTayang.addItem("15:30");
    cb_jamTayang.addItem("18:15");
    }//GEN-LAST:event_btn_film_500daysofsummerActionPerformed

    private void btn_film_interstellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_interstellarActionPerformed
        lbl_film.setText("Interstellar");
        filmDipilih = 2;
        
    cb_jamTayang.removeAllItems();
    cb_jamTayang.addItem("--Pilih Jam--");
    cb_jamTayang.addItem("12:45");
    cb_jamTayang.addItem("16:20");
    cb_jamTayang.addItem("19:45");
    }//GEN-LAST:event_btn_film_interstellarActionPerformed

    private void btn_film_avengersdoomsdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_film_avengersdoomsdayActionPerformed
        lbl_film.setText("Avengers Doomsday");
        filmDipilih = 3;
        
    cb_jamTayang.removeAllItems();
    cb_jamTayang.addItem("--Pilih Jam--");
    cb_jamTayang.addItem("13:15");
    cb_jamTayang.addItem("16:30");
    cb_jamTayang.addItem("21:00");
    }//GEN-LAST:event_btn_film_avengersdoomsdayActionPerformed

    private void btn_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesanActionPerformed
   if (input_nama.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama belum diisi!");
        return;
    }
    if (input_nohp.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No HP belum diisi!");
        return;
    }
    if (input_tanggal.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tanggal belum diisi!");
        return;
    }
    if (lbl_film.getText().equals(" ")) {
        JOptionPane.showMessageDialog(this, "Pilih film terlebih dahulu!");
        return;
    }
    if (lbl_kursi.getText().equals(" ") || kursiDipilih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih kursi terlebih dahulu!");
        return;
    }

    // 2. Ambil pilihan jam tayang dari JComboBox
    String jamTayang = cb_jamTayang.getSelectedItem().toString();
    if (jamTayang.equals("--Pilih Jam--") || jamTayang.isEmpty()) {
         JOptionPane.showMessageDialog(this, "Pilih jam tayang terlebih dahulu!");
         return;
    }

    // 3. Cek apakah kursi sudah terisi di memori lokal
    if (kursiTerisi[filmDipilih][kursiDipilih]) {
        JOptionPane.showMessageDialog(this, "Kursi " + lbl_kursi.getText() + " telah terisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Hitung Harga Secara Dinamis Berdasarkan Hari (Weekday vs Weekend)
    String tanggalInput = input_tanggal.getText().trim();
    int harga = 0;

    try {
        // Menentukan format tanggal yang wajib diinput user (Tahun-Bulan-Hari, Contoh: 2026-06-21)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate tanggalObjek = LocalDate.parse(tanggalInput, formatter);
        
        // Mengambil hari dari tanggal tersebut
        DayOfWeek hari = tanggalObjek.getDayOfWeek();

        // Logika penentuan harga
        if (hari == DayOfWeek.SATURDAY || hari == DayOfWeek.SUNDAY) {
            harga = 55000; // Harga untuk hari Sabtu & Minggu (Weekend)
        } else {
            harga = 40000; // Harga untuk hari Senin - Jumat (Weekday)
        }

    } catch (DateTimeParseException e) {
        // Jika user salah mengetikkan format tanggal, program tidak akan crash
        JOptionPane.showMessageDialog(this, "Format tanggal salah!\nGunakan format: YYYY-MM-DD\nContoh: 2026-06-21", "Error Tanggal", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Siapkan Data untuk disimpan
    String nama = input_nama.getText();
    String noHp = input_nohp.getText();
    String film = lbl_film.getText();
    String kursi = lbl_kursi.getText();

    // 6. Proses Simpan ke Database MySQL
    try {
        Connection conn = KoneksiDB.getKoneksi();
        
        String sql = "INSERT INTO pemesanan_tiket (nama, no_hp, tanggal_pemesanan, film, jam_tayang, kursi, harga) VALUES (?, ?, ?, ?, ?, ?, ?)";
        
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nama);
        pstmt.setString(2, noHp);
        pstmt.setString(3, tanggalInput);
        pstmt.setString(4, film);
        pstmt.setString(5, jamTayang);
        pstmt.setString(6, kursi);
        pstmt.setInt(7, harga); // Nilai harga dinamis hasil kalkulasi di atas
        
        pstmt.executeUpdate();
        
        // 7. Jika sukses di database, perbarui tampilan GUI lokal
        kursiTerisi[filmDipilih][kursiDipilih] = true;
        
        DefaultTableModel model = (DefaultTableModel) tabel_client.getModel();
        model.addRow(new Object[]{nama, noHp, tanggalInput, film, jamTayang, kursi, harga});
        
        JOptionPane.showMessageDialog(this, "Pemesanan berhasil disimpan! (Hari terdeteksi: " + LocalDate.parse(tanggalInput).getDayOfWeek() + ")");
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error saat menyimpan ke database: " + ex.getMessage());
    } 
    }//GEN-LAST:event_btn_pesanActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        input_nama.setText("");
        input_nohp.setText("");
        input_tanggal.setText("");
        lbl_film.setText("");
        lbl_kursi.setText("");
        
        filmDipilih = -1;
        kursiDipilih = -1;
        
        cb_jamTayang.removeAllItems();
    cb_jamTayang.addItem("--Pilih Jam--");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tabel_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_clientMouseClicked
        int row = tabel_client.getSelectedRow();

        if(row == -1){
            return;
        }

        int pilihan = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda ingin menghapus data ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION
        );

        if(pilihan == JOptionPane.YES_OPTION){

            DefaultTableModel model =
                (DefaultTableModel) tabel_client.getModel();

            model.removeRow(row);

            JOptionPane.showMessageDialog(
                this,
                "Data berhasil dihapus!"
            );
        }
    }//GEN-LAST:event_tabel_clientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cinema().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDENTITAS;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_film_500daysofsummer;
    private javax.swing.JButton btn_film_avengersdoomsday;
    private javax.swing.JButton btn_film_interstellar;
    private javax.swing.JButton btn_film_thedarkknight;
    private javax.swing.JButton btn_kursi_A1;
    private javax.swing.JButton btn_kursi_A2;
    private javax.swing.JButton btn_kursi_A3;
    private javax.swing.JButton btn_kursi_A4;
    private javax.swing.JButton btn_kursi_A5;
    private javax.swing.JButton btn_kursi_A6;
    private javax.swing.JButton btn_kursi_B1;
    private javax.swing.JButton btn_kursi_B2;
    private javax.swing.JButton btn_kursi_B3;
    private javax.swing.JButton btn_kursi_B4;
    private javax.swing.JButton btn_kursi_B5;
    private javax.swing.JButton btn_kursi_B6;
    private javax.swing.JButton btn_kursi_C1;
    private javax.swing.JButton btn_kursi_C2;
    private javax.swing.JButton btn_kursi_C3;
    private javax.swing.JButton btn_kursi_C4;
    private javax.swing.JButton btn_kursi_C5;
    private javax.swing.JButton btn_kursi_C6;
    private javax.swing.JButton btn_kursi_D1;
    private javax.swing.JButton btn_kursi_D2;
    private javax.swing.JButton btn_kursi_D3;
    private javax.swing.JButton btn_kursi_D4;
    private javax.swing.JButton btn_kursi_D5;
    private javax.swing.JButton btn_kursi_D6;
    private javax.swing.JButton btn_pesan;
    private javax.swing.JComboBox<String> cb_jamTayang;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_nohp;
    private javax.swing.JTextField input_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_film;
    private javax.swing.JLabel lbl_gif;
    private javax.swing.JLabel lbl_kursi;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tabel_client;
    // End of variables declaration//GEN-END:variables
}
